export const APROBADO = 'APROBADO'
export const RECHAZADO = 'RECHAZADO'
export const PENDIENTE = 'PENDIENTE'

export const CONVOCATORIA_FINALIZADA = 'FINALIZADA'
export const CONVOCATORIA_ABIERTA = 'ABIERTA'